# workflow to run tests on pull request to master

name: Backend CI 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set Up JDK 1.8
      - uses: actions/checkout@v2
        with: 
          java-version: 1.8

      # build
      - name: Gradle Build
        run: ./gradlew build
      
      - name: Gradle Test
        run: ./gradlew test

    

